
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:photo_manager/photo_manager.dart';
import '../../data/models/memory_story.dart';
import '../../shared/widgets/navigation_menu/app_bottom_nav.dart';
import '../../shared/widgets/navigation_menu/bottom_nav_controller.dart';

class StoryView extends StatelessWidget {
  const StoryView({super.key});

  @override
  Widget build(BuildContext context) {
    Get.find<BottomNavController>().markTab(BottomNavTab.stories);
    return Scaffold(
      appBar: AppBar(title: const Text('Memories')),
      bottomNavigationBar: const AppBottomNav(),
      body: FutureBuilder<List<MemoryStory>>(
        // Stories generated by AiPipelineService — stub empty list for now
        future: Future.value([]),
        builder: (context, snap) {
          if (snap.connectionState == ConnectionState.waiting) {
            return const Center(child: CircularProgressIndicator());
          }
          final stories = snap.data ?? [];
          if (stories.isEmpty) {
            return const _EmptyMemories();
          }
          return ListView.builder(
            padding: const EdgeInsets.all(16),
            itemCount: stories.length,
            itemBuilder: (_, index) =>
                _StoryCard(story: stories[index]),
          );
        },
      ),
    );
  }
}

class _StoryCard extends StatelessWidget {
  final MemoryStory story;
  const _StoryCard({required this.story});

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () => _openSlideshow(context),
      child: Container(
        height: 220,
        margin: const EdgeInsets.only(bottom: 16),
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(16),
          color: Colors.grey.shade200,
        ),
        child: Stack(
          fit: StackFit.expand,
          children: [
            // Cover image
            ClipRRect(
              borderRadius: BorderRadius.circular(16),
              child: FutureBuilder(
                future: _loadCover(story.coverItem.id),
                builder: (_, snap) => snap.hasData
                    ? Image.memory(snap.data!, fit: BoxFit.cover)
                    : Container(color: Colors.grey.shade300),
              ),
            ),
            // Gradient overlay
            Container(
              decoration: BoxDecoration(
                borderRadius: BorderRadius.circular(16),
                gradient: const LinearGradient(
                  begin: Alignment.topCenter,
                  end: Alignment.bottomCenter,
                  colors: [Colors.transparent, Colors.black54],
                ),
              ),
            ),
            // Text info
            Positioned(
              left: 16,
              right: 16,
              bottom: 16,
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(story.title,
                      style: const TextStyle(
                          color: Colors.white,
                          fontSize: 18,
                          fontWeight: FontWeight.bold)),
                  const SizedBox(height: 4),
                  Text(
                    '${story.photoCount} photos  •  ${story.timeAgoLabel}',
                    style: const TextStyle(color: Colors.white70, fontSize: 13),
                  ),
                ],
              ),
            ),
            // Dismiss button
            Positioned(
              top: 8,
              right: 8,
              child: IconButton(
                icon: const Icon(Icons.close, color: Colors.white),
                onPressed: () {/* story.dismiss() + remove from list */},
              ),
            ),
          ],
        ),
      ),
    );
  }

  void _openSlideshow(BuildContext context) {
    // Full-screen animated slideshow with music
    showDialog(
      context: context,
      barrierColor: Colors.black,
      builder: (_) => _SlideshowDialog(story: story),
    );
  }

  Future<dynamic> _loadCover(String assetId) async {
    final asset = await AssetEntity.fromId(assetId);
    return asset?.thumbnailDataWithSize(const ThumbnailSize(600, 400));
  }
}

class _SlideshowDialog extends StatefulWidget {
  final MemoryStory story;
  const _SlideshowDialog({required this.story});

  @override
  State<_SlideshowDialog> createState() => _SlideshowDialogState();
}

class _SlideshowDialogState extends State<_SlideshowDialog> {
  int _index = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.black,
      body: Stack(
        children: [
          PageView.builder(
            itemCount: widget.story.items.length,
            onPageChanged: (i) => setState(() => _index = i),
            itemBuilder: (_, index) {
              final item = widget.story.items[index];
              return FutureBuilder(
                future: _loadFull(item.id),
                builder: (_, snap) => snap.hasData
                    ? Image.memory(snap.data!, fit: BoxFit.contain)
                    : const Center(
                    child: CircularProgressIndicator(color: Colors.white)),
              );
            },
          ),
          // Close button
          Positioned(
            top: 40,
            left: 16,
            child: IconButton(
              icon: const Icon(Icons.close, color: Colors.white),
              onPressed: () => Navigator.of(context).pop(),
            ),
          ),
          // Counter
          Positioned(
            top: 40,
            right: 16,
            child: Text(
              '${_index + 1} / ${widget.story.items.length}',
              style: const TextStyle(color: Colors.white),
            ),
          ),
        ],
      ),
    );
  }

  Future<dynamic> _loadFull(String assetId) async {
    final asset = await AssetEntity.fromId(assetId);
    return asset?.originBytes;
  }
}

class _EmptyMemories extends StatelessWidget {
  const _EmptyMemories();

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: const [
          Icon(Icons.auto_awesome, size: 64, color: Colors.grey),
          SizedBox(height: 16),
          Text('No Memories yet',
              style: TextStyle(fontSize: 18, fontWeight: FontWeight.w500)),
          SizedBox(height: 8),
          Text(
            'Add at least 5 photos to a month\nand Memories will appear here.',
            textAlign: TextAlign.center,
            style: TextStyle(color: Colors.grey),
          ),
        ],
      ),
    );
  }
}